<a href="https://colab.research.google.com/github/MarcoLuw/semal27-stereoqueereval/blob/main/experiments/StereoQueerEval_task1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

In [ ]:
dataset1 = pd.read_csv("StereoQueerEval_EN_training.tsv", sep="\t")
dataset2 = pd.read_csv("StereoQueerEval_IT_training.tsv", sep="\t")
dataset3 = pd.read_csv("StereoQueerEval_NL_training.tsv", sep="\t")

In [ ]:
dataset1.head(n=10)

,StereoQueerEval_id,yt_title,yt_description,yt_comment,stereotype,hate_speech,target
0,training_EN_0001,[CHANNEL]: Lesbian denied communion at funeral,[CHANNEL] speaks to Barbara Johnson who says a...,She's living in unrepentant defiance to God's ...,yes,yes_explicit,individual_l
1,training_EN_0002,GOP Congresswoman uses anti-trans slur in Hous...,Rep. Nancy Mace (R-SC) was challenged by Rep. ...,Rep Mace: Keep on being dedicated to truth and...,yes,yes_implicit,group_t
2,training_EN_0003,Kevin Smith defends his gay brother,"Kevin Smith supports gay rights, and defends h...","We all need Jesus, He said no homosexual shall...",yes,yes_implicit,"group_l,g"
3,training_EN_0004,Judge removes child from gay foster parents,A Utah judge removed a foster child from a les...,So can two black men adopt a little white girl...,yes,yes_implicit,group_l
4,training_EN_0005,Chechen leader Ramzan Kadyrov questioned on 'g...,Chechnya's leader Ramzan Kadyrov is questioned...,Of course west and US will hate him,yes,yes_implicit,group_g
5,training_EN_0006,Duck Dynasty' star: Homosexuality wrong,Gay rights advocates want the A&E network to c...,"For God, so loved the world that he gave his o...",yes,yes_explicit,group_lgbtqia+
6,training_EN_0007,Gay marriage: Ireland's big message for equali...,The Republic of Ireland has voted overwhelming...,"Wow, can't believe that anything anti gays wou...",no,no,none
7,training_EN_0008,Fencer kneels in protest against opponent she ...,USA Fencing disqualified fencer Stephanie Turn...,Say no to hate,no,no,none
8,training_EN_0009,NFL veteran opens up after coming out: I'll be...,"NFL veteran, Ryan Russell, who recently came o...",Should’ve kept fighting those desires. Just li...,yes,yes_explicit,individual_b
9,training_EN_0010,Fetishised and forgotten: Why bisexuals want a...,Bisexuals face hostility from their own LGBT c...,"straight men fetish me,straight women make me ...",yes,no,none

In [ ]:
dataset2.head()

,StereoQueerEval_id,yt_title,yt_description,yt_comment,stereotype,hate_speech,target
0,training_IT_0001,"Nivan transgender a 17 anni: ""Il mio percorso ...",Nivan è un ragazzo transgender Ftm di soli 17 ...,Sono transgender ma ho paura di dirlo ai miei ...,no,no,none
1,training_IT_0002,"Casillas annuncia di essere gay, poi parla di ...","Travolto dalle polemiche, Casillas è stato cos...",E cosa sarà mai guardate cosa succede nel mond...,no,yes_implicit,group_g
2,training_IT_0003,Schlein: «Con governo Meloni l’Italia è scivol...,«Sono sempre felice quando c’è il riconoscimen...,Ma fate silenzio il gay pride e finito ora and...,yes,yes_explicit,group_lgbtqia+
3,training_IT_0004,"Olimpiadi Parigi 2024, la pugile Imane Khelif ...",Dopo che Angela Carini alle Olimpiadi di Parig...,Donna Trans NON ESISTE! Un uomo non puo` diven...,yes,yes_explicit,group_t
4,training_IT_0005,"Roma Pride 2018, l'inno ""Ma che ti importa"": ""...",Sabato 9 giugno il Roma Pride scende in piazza...,Allora che vi importa se uno dice che prenderl...,no,yes_explicit,"group_g,lgbtqia+"

In [ ]:
dataset3.head()

,StereoQueerEval_id,yt_title,yt_description,yt_comment,stereotype,hate_speech,target
0,training_NL_0001,Non-binaire mensen kunnen binnenkort vragen om...,Binnenkort kunnen non-binaire mensen vragen om...,een schande dat ons geld hier naartoe gaat,no,yes_implicit,group_nb
1,training_NL_0002,Non-binaire mensen kunnen binnenkort vragen om...,Binnenkort kunnen non-binaire mensen vragen om...,"Ach shit,...et is idd 1 april natuurlijk😂....",no,yes_implicit,group_nb
2,training_NL_0003,Acceptatie lhbti+ op dieptepunt! ’Social media...,Ooit was Nederland een tolerant land en de hom...,"Nee, dit accepteren we niet.",no,yes_implicit,group_lgbtqia+
3,training_NL_0004,Pride Amsterdam staat onder spanning: ‘Ermee s...,Amsterdam - ooit de gay-capital maar anno nu a...,Op pride en lhbti gemeenschap mogen het zo gek...,yes,yes_explicit,group_lgbtqia+
4,training_NL_0005,Gehandicapte transgender rapper Arjen wil Nede...,Wij vonden een opmerkelijke verhaal in onze ma...,Een travestiet is niet hetzelfde als een trans...,no,no,none

In [ ]:
print(dataset1.shape)
print(dataset2.shape)
print(dataset3.shape)

(2989, 7)
(2400, 7)
(2238, 7)